[package]
name = "arenic_bevy"
version = "0.1.0"
edition = "2021"


[lib]
name = "arenic"
path = "src/lib.rs"

[dependencies]
bevy = "0.15"
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features=["Window", "Storage"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.134"
